version: "3.9"
services:
  gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth
      - mongodb
      - chat

  auth:
    build: ./auth-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/demo-auth

      - JWT_SECRET=neshaki
      - JWT_EXPIRES_IN=1h
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  chat:
    build: ./chat-service
    environment:
    - MONGO_URL=mongodb://mongodb:27017/chat_service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
volumes:
  mongo-data: